services:
  wp_db:
    image: mariadb:10.5
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: wp_pass
      MYSQL_ROOT_PASSWORD: root_pass
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "bash", "-lc", "exec 3<>/dev/tcp/127.0.0.1/3306 && echo -e 'quit' >&3 && exit 0 || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 12
      start_period: 15s

  wp_ctf:
    build: .
    depends_on:
      wp_db:
        condition: service_healthy
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: wp_db:3306
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: wp_pass
      WORDPRESS_DB_NAME: wordpress
    ports:
      - "8080:80"      # Web
      - "1337:1337"    # Banner
    volumes:
      - wp_data:/var/www/html
    healthcheck:
      test: ["CMD", "bash", "-lc", "curl -fsS http://127.0.0.1/ >/dev/null"]
      interval: 10s
      timeout: 5s
      retries: 6
      start_period: 20s

volumes:
  db_data:
  wp_data:
